version: "2"

services:
  elasticsearch:
    image: elasticsearch:5.2.1
    volumes:
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  app:
    image: geosearchapp:latest
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
